---
title: "Onset HOBO U-26 Dissolved Oxygen logger"
output: 
  html_document:
    css: "style.css"
---
### Supplies

- HOBO U26 DO logger with gray vinyl “calibration boot” cover

- YSI Pro-Plus to get a current barometric pressure reading

- Deionized water

- Sodium sulfite solution

- Cut-off graduated cylinder

- Laptop with HOBOware installed

- HOBO waterproof shuttle 

[HOBO U26 DO logger user manual
](https://www.onsetcomp.com/files/manual_pdfs/15603-B-MAN-U26x.pdf)

This logger needs to be calibrated before each deployment. Instant YSI DO readings should be collected at deployment and retrieval. 

### Connecting the Logger to a Computer or Waterproof Shuttle

To connect the logger to a computer, use either the Optic USB Base Station (BASE-U-4) or HOBO Waterproof Shuttle (U-DTW- 1) with a coupler (COUPLER2-C). 

1. Unscrew the pointed black cap on the communications end of the logger.

2. Attach the coupler to the base station or shuttle.

3. Insert the logger into the coupler, aligning the bump/arrow on the coupler with the notches on the logger. Be sure that it is properly seated in the coupler. If the logger has never been connected to the computer before, it may take a few seconds for the new hardware to be detected by the computer. If the computer still fails to recognize the device, unplug the shuttle from the computer’s USB port, and plug in again. Note: If you are using the HOBO Waterproof Shuttle as a base station with a computer, briefly press the coupler lever to put the shuttle into base station mode. A green LED on the shuttle or base station indicates good communication.

4. After logger communications are complete, remove the logger from the coupler. Make sure the o-ring is still in the groove inside the cap, and then reinstall the communications cap.

### Calibrating the Logger with the Lab Calibration Tool

Use the Lab Calibration tool in HOBOware to calibrate the logger before deploying it. In the two-step procedure, the logger is first calibrated to 100% saturation by placing it in water-saturated air. Then, you can calibrate the logger to 0% saturation by placing it in a sodium sulfite solution. The fresh water, logger, and sodium sulfite (if applicable) should be left out in the lab where the calibration is being done long enough so that they are at room temperature. If the logger was deployed previously, make sure the sensor is clean and dry (see Maintenance for more details). 

**To use the Lab Calibration tool:**

1. Connect the logger to the computer as described in the previous section. Stop the logger if it is currently logging or awaiting a coupler or delayed start.

2. From the Device menu, click Lab Calibration.

3. The current gain and offset adjustments are displayed in the top pane of the Lab Calibration window along with the date and time the last lab calibration was completed (if applicable). Completing Steps 1 through 3 in the Lab Calibration tool will result in new gain and offset adjustment values based on the current logger conditions.

4. Step 1: 100% Saturation
In “Step 1: 100% Saturation” in the Lab Calibration window, enter the barometric pressure for your current location. Use the YSI to get the current barometric pressure.

- Make sure the logger either has the protective guard or the anti-fouling guard installed (whichever guard you plan to use in the deployment) so that the sensor is covered.

- Remove the small sponge from the calibration boot, and wet the sponge with deionized water. It should be damp, but not sopping.

- Place the sponge in the gray calibration boot.

- Insert the logger in the calibration boot so that there is approximately a 1 cm (0.5 inch) overlap between the end of the boot and the body of the logger. This will ensure there is enough space between the end of the logger and the sponge (the logger should not be pressed up tightly against the sponge).

- Set a timer on your phone for 15 minutes.

- After 15 minutes, click the “Get DO value from the logger” button to display the 100% saturation results. 

- Click the Next button to proceed to “Step 2: 0% Saturation.

5. Step 2: 0% Saturation 

- If the logger will be deployed in water with DO levels greater than 4 mg/L, click the “Skip this Step” button. Otherwise, continue with the following procedure.

- Make sure the logger either has the protective guard or the anti-fouling guard installed (whichever guard you plan to use in the deployment) so that the sensor is covered.

- Pour the sodium sulfite into the cut-off graduated cylinder to the fill line.

- Place the sensor end of the logger into the solution so that the entire protective guard or anti-fouling guard and at least 2.5 cm (1 inch) of the logger body are submerged in the beaker. Allow it to rest on the bottom of the beaker.

- Set your phone timer for another 15 minutes

- Click the “Get DO value from the logger” button to display the 0% saturation results.

- Click the Next button to proceed to “Step 3: Finish.”

6. Step 3: Finish

- The results from the first two steps are displayed as well as the overall calibration results and the new gain and offset adjustment values. If you are satisfied with the results, click the “Send Calibration to Logger” button. The logger will then be calibrated based on the new values. These values will not take effect until the logger is launched.

### Launching the Logger

After calibrating the logger, it needs to be launched to configure it before taking it to the field for deployment. 

1. With the logger connected to the computer, open HOBOware. From the Device menu, select Launch.

2. Select both the DO and Temperature channels to log. Note: HOBOware provides the option of recording the current battery voltage at each logging interval, which is disabled by default. Recording battery life at each logging interval takes up memory and therefore reduces logging duration. It is recommended that you only record battery voltage for diagnostic purposes. Even with the channel disabled, a bad battery event will still be recorded.

3. Select a logging interval. This will typically be an interval of 15 minutes. 

4. Choose when to start logging and click the Start button.

- Note: Because deployment programming does not typically include an exact end time/date, the program will warn you that the DO filter will expire before retrieval. If the sensor’s listed expiration date is not within the time frame of deployment, select “continue anyway”.

5. Remove the logger from the coupler and screw the communications cap back on the logger.

### Deploying the Logger

The logger is designed to be easy to deploy in many environments. Follow these guidelines when deploying it:

- Remove the calibration boot before deploying the logger.

- Make sure the logger is located where it will receive an unrestricted flow of the water being monitored to the sensor.

- Make sure the logger is fully submerged and not in direct sunlight to minimize temperature changes that are unrelated to water temperature.

- When deploying the logger in rivers, streams, and ponds, insert the logger in a PVC or ABS pipe for protection from debris (if possible). The pipe should have enough holes to ensure good circulation of water to the sensor.

- If possible, position the logger so the sensor face is oriented vertically. After deploying in the water, move the logger around slightly to eliminate any bubbles that may have formed.

- Do not deploy the logger in freezing water with moving ice where the logger could be crushed.

- Use the optional anti-fouling guard to protect against fouling. Unscrew the protective guard and replace it with the anti-fouling guard.

- If fouling is expected during deployment, use field calibration readings from both the beginning and end of the deployment as described in the next section. These readings can then be entered into the HOBOware Dissolved Oxygen Assistant to compensate for any measurement drift due to fouling. Scrub fouling off the logger body with a plastic bristle brush. Use a soft sponge to remove fouling from the guard.

- When deploying the logger in salt water, you will need a conductivity value to enter in the Dissolved Oxygen Assistant that adjusts the data from the logger for salinity. If the salinity is constant through the deployment, you will need a single salinity reading from either a conductivity meter or salinometer. However, if the conductivity changes, then you will need a data file with salinity or specific conductivity readings for the entire deployment. Consider deploying a HOBO Conductivity logger (U24-002) next to this DO logger to use the resulting data file for salinity data.

- To generate a percent saturation series, you will need to deploy a barometric pressure logger (such as a HOBO Water Level Logger, U20-001-0x) or have access to a nearby weather station to gather barometric pressure data. This data is necessary for the Dissolved Oxygen Assistant to calculate percent saturation.

### Taking Field Calibration Readings

If fouling is expected during the deployment, you can take calibration readings at the beginning and end of the deployment to enter in the Dissolved Oxygen Assistant. This will adjust the data from the logger to compensate for any measurement drift due to fouling. 

1. To take calibration readings using a DO field meter:

2. The logger must be logging. Take a DO measurement of the water where the logger is being deployed. If using a meter, make sure it is calibrated and allow time for the meter probe to stabilize (this will occur when three meter measurements taken in a row are within your accuracy tolerance).

3. Record the reading, date, and time of the measurement in a field notebook.

4. At the end of the deployment, repeat steps 1 and 2.

### Post-processing and Offloading Data

To process the collected data, you must use the HOBOware Pro software on the laboratory laptop, as the DO assistant software is not available in the free software version. All necessary calibration samples have been noted in the above sections. 

**You must offload both conductivity and barometric pressure files in order to use the DO assistant.** 

**To offload data using the DO Assistant:**

1. Connect the logger to the computer as described in the first section. Stop the logger.

2. Select “device readout”.

3. Within the Plot Setup window, select “Dissolved Oxygen Assistant”.

4. In the Adjust for Salinity window, select “Specific Conductance”, and select the Specific Conductance datafile previously uploaded from the conductivity logger. If the conductivity logger was not deployed, select “Salinity”, and enter the field YSI value collected before deployment. 

5. Within the Use Barometric Pressure (for percent saturation) window, select “Barometric Datafile”, and select the barometric pressure file previously uploaded from the HOBO Water Level Logger. If no barometric pressure monitor was deployed, select “Barometric Data Value”, and enter the barometric pressure value gathered from the site’s nearest weather station. 

6. In the Perform Field Calibration window, select “Using Dissolved Oxygen Meter”, and enter the DO values taken at deployment and retrieval. 

7. Plot the information, label the file with date and location, and save the file to the shared drive. 

8. Detach the DO logger from the coupler, and unplug the Optic USB Base Station from the computer’s USB port. 

9. Thoroughly rinse the DO logger’s sensor with deionized water. Scrub away any fouling from the logger’s body using a soft-bristled brush. If barnacles have begun to form on the logger’s body, ensure the logger is tightly sealed (as for deployment) before soaking in vinegar overnight. Fouling should scrub away easily the next day. 

10. Ensure the sponge in the logger’s calibration boot is damp (not soaking) with deionized water, and slide the boot over the logger’s sensor for storage. 
