---
title: "Onset HOBO MX2501 pH logger"
output: 
  html_document:
    css: "style.css"
favicon: "img/favicon-32x32.png"
---

### Warning: Do not let pH sensor dry
pH sensors are very sensitive to desiccation. If the sensor is removed from liquid for more than a minute or two, it will be damaged or destroyed. Always keep the sensor in either the storage solution, buffer calibration solution, or the deployment medium. Remember, "if it dries, it dies."

### App download

1. Download the HOBOconnect app to a phone or tablet from the App Store® or Google Play™. Download the app to a Windows computer from [HOBOconnect for windows](www.onsetcomp.com/products/software/hoboconnect).

2. Open the app and enable Bluetooth in the device settings if prompted.

3. Wake up the logger by pushing the switch on the mounting end of the logger into the gap beneath the mounting lanyard. 

4. Tap Devices and then tap the logger tile in the app to connect to the logger. 


### Calibration

**Supplies**

* Deionized or distilled water and a squirt bottle to rinse the pH sensor. 
* The logger with the pH electrode installed and the copper guard removed. 
* Calibration solution (also called buffer solution) poured into beakers. All three buffers are available in a kit (MX2500-CAL-KIT) or individually (MX2500-CAL-4, MX2500-CAL-7, or MX2500-CAL-10)

**Procedure**

1. If the sensor is in the storage solution, unscrew the clear storage cap and remove it from the logger.  

2. Once removed, screw the black deployment cap onto the logger. This keeps the sensor tip attached to the logger.

3. In the HOBOconnect app, tap Devices.

4. If the logger was previously configured with Bluetooth Always Off, press the gray rubber switch on the top of logger to wake it up. 

5. Tap the logger in the app to connect to it. If you have been calibrating multiple loggers, make sure the device serial number listed in the app matches the device in hand.

6. Tap Calibrate if you are not automatically prompted to calibrate the logger. 

7. Use a squirt bottle to rinse the pH sensor with deionized or distilled water. Then use a squirt bottle filled with pH 7 buffer solution to buffer-rinse the sensor. 

8. Place the sensor end of the logger in the pH 7 solution and tap Start. Make sure the sensor end cap, temperature sensor, and closure cap are submerged in the solution. A message will appear when the pH reading is stable, but wait a few more minutes until the mV readings stabilize. Then tap Confirm. 

9. Rinse the pH sensor with deionized or distilled water, then rinse with the next buffer solution. 

10. If you are using the pH 4 buffer, place the sensor end in the pH 4 solution and tap Start. If you are not using the pH 4 buffer, tap Skip and go to step 12. 

11. Once the pH and mV readings are stable, tap Confirm. Rinse the pH sensor with deionized or distilled water. Then rinse with the next buffer solution. 

12. If you are using the 10 buffer, place the sensor end in the pH 10 solution and then tap Start. Once the pH reading is stable, tap Confirm. If you are not using the pH 10 buffer, tap Skip. 

13. Verify that the slope and offset are acceptable and tap Save. If the slope and offset are not acceptable, tap the back arrow and repeat the calibration steps in this section as needed. 

14. Rinse the pH sensor with deionized or distilled water again. 

**NOTE: If you are not deploying the logger immediately, place the pH electrode in storage-solution. Unscrew the sensor end cap installed on the sensor end of the logger. If the clear storage cap is empty, pour in storage-solution to the marked fill line. Carefully screw the clear cap with storage-solution onto the logger. Only use storage-solution in the clear cap; do not use water. Do not use the copper guard when the pH electrode is in storage solution**

### Logger programming and deployment

**Programming**

1. Get the pH logger and press in the gray button on the top while the HOBOconnect app is open on your phone. You should see the logger pop up on the app from its home screen.

1. Select "Customize Configuration & Start." Select your desired logging interval and your desired logging start date and time. Triple-check that you have selected the correct start time.

1. Select "Start" from this screen or go back to the home screen and select "Start with Saved Configuration." The logger will start logging at the specifed time and interval. 

**Deployment**

1. Once at site remove the cap covering the sensor.

2. make sure the sensor does not become disconnected from the main body of the logger; some of them are loose.

3. Secure the closure cap onto where the storage lid was previously and then deploy the logger.

4. Deploy as appropriate for the site.

### Data Retrieval 
**Note: during this process the more loggers you add to your device the slower and choppier the app will run. This is ok, but make sure that you are patient with the app.**

1. During retrieval, make sure that the storage cap is returned to the logger as quickly as possible. At this stage it is okay to use water found at the site as the storage liquid, but it must be switched out to the proper solution eventually.

1. Once the logger is collected, launch the app from your device and then hit the gray button at the top of the logger, it should show up on the HOBOconnect app.

1. Select the logger, then select "Stop Logger" to stop logging.

1. Select the “Download Data."

1. Once the data is downloaded, go back to the app homescreen and select “Data” from the menu on the bottom of the screen.

1. Select “export and share.” At the top of the screen, find the data you downloaded and export it as a CSV file.

1. Once exported the app will pop up with a bulk export summary where you can share the exported data.

1. From there you can move it straight into the project-specific Google Drive folder. You may need to install the Google Drive app on your phone. 

1. Once all relevant data is collected and moved into the Google drive, rename the files according to the project-specific naming conventions. 

1. If you haven't already, replace water in the storage lid with the proper storage solution and clean the sensor. Make sure to keep the sensor damp at all times.

1. Store safely

<br />
<br />
